[tasks.clean]
clear = true
script = """
cargo clean
rm -rf ./neardev/
rm -rf ./deploy/
"""

[tasks.prepare]
script = """
rustup target add wasm32-unknown-unknown && rustup install 1.69 && rustup default 1.69 && cargo --version
"""


[tasks.test]
clear = true
script = """
#!/usr/bin/env zsh

set -e
DEFAULT_ARCH="$(rustc -vV | awk '/host:/ {print $2}')"
cargo test --target $DEFAULT_ARCH
"""

[tasks.build]
args = ["build", "--target", "wasm32-unknown-unknown", "--release"]
command = "cargo"

[tasks.optimize]
dependencies = ["build"]
script = """
#!/usr/bin/env zsh

set -e
WASM_PATH="$(find ./target/wasm32-unknown-unknown/release -maxdepth 1 -name "*.wasm")"

mkdir -p ./deploy/
wasm-tools strip "$WASM_PATH" > "./deploy/$(basename $WASM_PATH)"
# TODO: Figure out which wasm-opt flags don't break contracts
"""

[tasks.deploy]
dependencies = ["optimize"]
script = """
#!/usr/bin/env zsh

set -e
RAW_WASM_PATH="$(find ./target/wasm32-unknown-unknown/release -maxdepth 1 -name "*.wasm")"
WASM_PATH="./deploy/$(basename $RAW_WASM_PATH)"

near deploy \
  --wasmFile $WASM_PATH \
  --accountId "$1" \
  --initFunction new \
  --initArgs "$(./args.sh)"
"""

[tasks.dev-deploy]
dependencies = ["build"]
script = """
#!/usr/bin/env zsh

set -e
WASM_PATH="$(find ./target/wasm32-unknown-unknown/release -maxdepth 1 -name "*.wasm")"

near dev-deploy --wasmFile $WASM_PATH

if ! grep -q "^NEXT_PUBLIC_$(cat ./neardev/dev-account.env)$" ../client/.env; then echo "NEXT_PUBLIC_$(cat ./neardev/dev-account.env)" >> ../client/.env; fi
"""

[tasks.call]
script = """
#!/usr/bin/env zsh

set -e
[ -f ./neardev/dev-account ] || (echo "Contract must be deployed"; false)
near call "$(<./neardev/dev-account)" "$@"
"""

[tasks.call-self]
script = """
#!/usr/bin/env zsh

set -e
[ -f ./neardev/dev-account ] || (echo "Contract must be deployed"; false)
near call "$(<./neardev/dev-account)" "$@" --accountId "$(<./neardev/dev-account)"
"""

[tasks.view]
script = """
#!/usr/bin/env zsh

set -e
[ -f ./neardev/dev-account ] || (echo "Contract must be deployed"; false)
near view "$(<./neardev/dev-account)" "$@"
"""